services:
  bsc-scanner:
    build: .
    container_name: bsc-scanner
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "127.0.0.1:9105:8002"